version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LLM_API_KEY=${LLM_API_KEY:-}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./configs/mibs:/app/configs/mibs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - snmp-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - snmp-network

volumes:
  redis-data:

networks:
  snmp-network:
    driver: bridge
