api:
  port: 8080
  host: "0.0.0.0"

snmp:
  version: "2c"
  community: "public"
  timeout: 5
  retries: 3

mib:
  repository_path: "./configs/mibs"
  cache_size: 1000

llm:
  api_key: ""  # Set this in environment variable
  model: "gpt-4"
  max_tokens: 1000
  temperature: 0.7

redis:
  host: "localhost"  # Will be overridden by environment in Docker
  port: 6379
  db: 0
